# Generated by Django 2.0.2 on 2018-02-17 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postText', models.TextField()),
                ('publishDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='publicDate',
        ),
        migrations.AddField(
            model_name='question',
            name='publishDate',
            field=models.DateTimeField(null=True, verbose_name='Question publish date'),
        ),
    ]
